//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCostBenefitAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitsProfile
    {
        public int BenefitsProfileId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProposedProduct { get; set; }
        public Nullable<System.DateTime> DateConducted { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<int> BenefitsCategoryId { get; set; }
        public Nullable<int> Year1 { get; set; }
        public Nullable<int> Year2 { get; set; }
        public Nullable<int> Year3 { get; set; }
        public Nullable<int> Year4 { get; set; }
        public Nullable<int> Year5 { get; set; }
        public Nullable<int> Year6 { get; set; }
        public Nullable<int> Year7 { get; set; }
        public Nullable<int> Year8 { get; set; }
        public Nullable<int> Year9 { get; set; }
        public Nullable<int> Year10 { get; set; }
    
        public virtual BenefitsCategory BenefitsCategory { get; set; }
        public virtual ProjectDetails ProjectDetails { get; set; }
        public virtual StandartUsers StandartUsers { get; set; }
    }
}
