//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCostBenefitAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectDetails()
        {
            this.Answers = new HashSet<Answers>();
            this.BenefitsProfile = new HashSet<BenefitsProfile>();
            this.CostProfile = new HashSet<CostProfile>();
        }
    
        public int ProjectId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime ProjectEstimatedStartDate { get; set; }
        public System.DateTime ProjectEstimatedCompletionDate { get; set; }
        public string ProjectDescription { get; set; }
        public string ExpectedBenefits { get; set; }
        public string StakeholdersActors { get; set; }
        public string RelatedBusinessProcesses { get; set; }
        public int ProjectGoal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answers> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitsProfile> BenefitsProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostProfile> CostProfile { get; set; }
        public virtual StandartUsers StandartUsers { get; set; }
    }
}
